const PAGE_SIZE = { rows: 2000, cols: 60 };
const STORAGE_KEY = 'clara-planilha-v1';
const DEFAULT_SETTINGS = { density: 'comfortable', gridlines: true, gridTheme: 'formal', selectionColor: '#8056a6', autoSave: true };
let state = loadState();
let activeCell = { row: 0, col: 0 };
let history = [], historyIndex = -1;
let clipboardBuffer = '';
let activeFilterColumn = null;
let dragClearActive = false;
let dragClearMoved = false;
let dragClearCells = new Set();
const grid = document.getElementById('sheetGrid');
const formulaInput = document.getElementById('formulaInput');
const nameBox = document.getElementById('nameBox');

function pageSize() { return PAGE_SIZE; }
function blankSheet(name) { return { name, columnNames: Array.from({length: PAGE_SIZE.cols}, (_, index) => columnName(index)), cells: Array.from({length: PAGE_SIZE.rows}, () => Array(PAGE_SIZE.cols).fill('')), colors: Array.from({length: PAGE_SIZE.rows}, () => Array(PAGE_SIZE.cols).fill('')), formats: Array.from({length: PAGE_SIZE.rows}, () => Array.from({length: PAGE_SIZE.cols}, () => ({}))) }; }
function loadState() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); if (saved?.sheets?.length) { saved.zoom = Number(saved.zoom) || 100; saved.columnFilters = saved.columnFilters || {}; saved.settings = { ...DEFAULT_SETTINGS, ...(saved.settings || {}) }; if (saved.settings.selectionColor === '#a66a3f') saved.settings.selectionColor = DEFAULT_SETTINGS.selectionColor; return saved; } } catch (_) {} return { fileName: 'Meu planejamento', active: 0, zoom: 100, columnFilters: {}, settings: { ...DEFAULT_SETTINGS }, sheets: [blankSheet('Planejamento')] }; }
function columnName(index) { let name = ''; for (let n = index + 1; n; n = Math.floor((n - 1) / 26)) name = String.fromCharCode(65 + ((n - 1) % 26)) + name; return name; }
function cellRef(row, col) { return `${columnName(col)}${row + 1}`; }
function currentSheet() { return state.sheets[state.active]; }
function ensureSheetSize(sheet, rows, cols) { if (!sheet.columnNames) sheet.columnNames = []; while (sheet.columnNames.length < cols) sheet.columnNames.push(columnName(sheet.columnNames.length)); while (sheet.cells.length < rows) sheet.cells.push([]); sheet.cells.forEach(row => { while (row.length < cols) row.push(''); }); if (!sheet.colors) sheet.colors = []; while (sheet.colors.length < sheet.cells.length) sheet.colors.push([]); sheet.colors.forEach(row => { while (row.length < cols) row.push(''); }); if (!sheet.formats) sheet.formats = []; while (sheet.formats.length < sheet.cells.length) sheet.formats.push([]); sheet.formats.forEach(row => { while (row.length < cols) row.push({}); }); }
function render() {
  const sheet = currentSheet();
  const { rows, cols } = pageSize();
  ensureSheetSize(sheet, rows, cols);
  state.settings = { ...DEFAULT_SETTINGS, ...(state.settings || {}) };
  document.body.dataset.density = state.settings.density;
  document.body.dataset.gridTheme = state.settings.gridTheme;
  document.body.classList.toggle('hide-gridlines', !state.settings.gridlines);
  document.documentElement.style.setProperty('--selection-color', state.settings.selectionColor);
  const filters = state.columnFilters || {};
  grid.innerHTML = `<thead><tr><th></th>${Array.from({length: cols}, (_, c) => `<th><div class="column-header"><input class="column-name-input" value="${escapeHtml(sheet.columnNames[c])}" data-column-name="${c}" aria-label="Nome da coluna ${columnName(c)}"><button class="column-filter-button ${filters[c] ? 'active' : ''}" data-filter-column="${c}" title="Filtrar coluna ${sheet.columnNames[c]}" aria-label="Filtrar coluna ${sheet.columnNames[c]}">▼</button></div></th>`).join('')}</tr></thead><tbody>${sheet.cells.slice(0, rows).map((row, r) => { const matches = Object.entries(filters).every(([column, values]) => !values?.length || values.includes(String(row[Number(column)] ?? ''))); return `<tr class="${matches ? '' : 'filtered-row'}"><td class="row-number">${r + 1}</td>${row.slice(0, cols).map((value, c) => { const format = sheet.formats[r][c] || {}; return `<td class="cell ${value.startsWith('=') ? 'formula' : ''}" style="background-color:${sheet.colors[r][c] || ''};font-weight:${format.bold ? '700' : '400'};font-style:${format.italic ? 'italic' : 'normal'};text-align:${format.align || 'left'}" contenteditable="true" data-row="${r}" data-col="${c}" data-formula="${value.startsWith('=')}">${displayValue(value)}</td>`; }).join('')}</tr>`; }).join('')}</tbody>`;
  document.getElementById('fileName').value = state.fileName;
  document.getElementById('cellColor').value = currentSheet().colors[activeCell.row]?.[activeCell.col] || '#ffffff';
  document.getElementById('zoomInput').value = state.zoom;
  grid.style.zoom = `${state.zoom}%`;
  renderTabs(); selectCell(activeCell.row, activeCell.col, false); applySearch();
}
function displayValue(value) { return value.startsWith('=') ? calculate(value) : value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'); }
function calculate(formula) {
  try {
    let expression = formula.slice(1).replace(/SUM\(([^)]+)\)/gi, (_, range) => rangeValue(range).reduce((a,b) => a + (Number(b) || 0), 0));
    expression = expression.replace(/([A-Z]+)(\d+)/g, (_, col, row) => JSON.stringify(currentSheet().cells[Number(row)-1]?.[columnIndex(col)] || 0));
    if (!/^[\d\s+*/().,'"-]+$/.test(expression)) return '#ERRO';
    return String(Function(`"use strict"; return (${expression})`)());
  } catch (_) { return '#ERRO'; }
}
function columnIndex(name) { return [...name].reduce((n, char) => n * 26 + char.charCodeAt(0) - 64, 0) - 1; }
function rangeValue(range) { const [start, end = start] = range.split(':'); const a = start.match(/([A-Z]+)(\d+)/i), b = end.match(/([A-Z]+)(\d+)/i); if (!a || !b) return []; const values = []; for (let r = +a[2]-1; r <= +b[2]-1; r++) for (let c = columnIndex(a[1].toUpperCase()); c <= columnIndex(b[1].toUpperCase()); c++) values.push(currentSheet().cells[r]?.[c]); return values; }
function selectCell(row, col, focus = true) { activeCell = {row, col}; document.querySelectorAll('.cell.selected').forEach(el => el.classList.remove('selected')); const cell = document.querySelector(`[data-row="${row}"][data-col="${col}"]`); if (!cell) return; cell.classList.add('selected'); nameBox.textContent = cellRef(row, col); formulaInput.value = currentSheet().cells[row][col]; document.getElementById('selectionInfo').textContent = '1 célula selecionada'; if (focus) { cell.focus(); placeCaretAtEnd(cell); } }
function placeCaretAtEnd(el) { const range = document.createRange(); range.selectNodeContents(el); range.collapse(false); const sel = window.getSelection(); sel.removeAllRanges(); sel.addRange(range); }
function commitCell(cell, value) { const row = +cell.dataset.row, col = +cell.dataset.col, sheet = currentSheet(), normalized = value.trim().toLowerCase(); if (sheet.cells[row][col] === value) return; if (normalized && sheet.cells.some((cells, rowIndex) => cells.some((existing, colIndex) => rowIndex !== row || colIndex !== col ? String(existing).trim().toLowerCase() === normalized : false))) { pushHistory(); sheet.cells[row][col] = ''; cell.innerHTML = ''; cell.dataset.formula = 'false'; cell.classList.remove('formula'); persist(); toast('Valor duplicado removido'); return; } pushHistory(); sheet.cells[row][col] = value; cell.innerHTML = displayValue(value); cell.dataset.formula = value.startsWith('='); cell.classList.toggle('formula', value.startsWith('=')); persist(); }
function pushHistory() { history = history.slice(0, historyIndex + 1); history.push(JSON.stringify(state)); historyIndex++; if (history.length > 30) { history.shift(); historyIndex--; } }
function persist(force = false) { if (state.settings?.autoSave === false && !force) { document.getElementById('saveStatus').textContent = 'Não salvo'; return; } localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); document.getElementById('saveStatus').textContent = 'Salvo agora'; setTimeout(() => document.getElementById('saveStatus').textContent = 'Salvo localmente', 1200); }
function renderTabs() { document.getElementById('sheetTabs').innerHTML = state.sheets.map((sheet, i) => `<button class="sheet-tab ${i === state.active ? 'active' : ''}" data-sheet="${i}">${sheet.name}</button>`).join(''); }
function toast(message) { const el = document.getElementById('toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2200); }
function openFilterMenu(column, button) { const sheet = currentSheet(), values = [...new Set(sheet.cells.slice(0, pageSize().rows).map(row => String(row[column] ?? '')))].sort((a, b) => a.localeCompare(b)); const selected = state.columnFilters?.[column] || values.slice(); const menu = document.getElementById('filterMenu'); menu.innerHTML = `<h3 class="filter-menu-title">Filtrar ${columnName(column)}</h3><input class="filter-menu-search" placeholder="Pesquisar valor" aria-label="Pesquisar valor"><div class="filter-values">${values.map((value, index) => `<label class="filter-value"><input type="checkbox" data-filter-value="${escapeHtml(value)}" ${selected.includes(value) ? 'checked' : ''}><span>${escapeHtml(value || '(vazio)')}</span></label>`).join('')}</div><div class="filter-menu-actions"><button type="button" id="clearColumnFilter">Limpar</button><button type="button" class="filter-apply" id="applyColumnFilter">Aplicar</button></div>`; const rect = button.getBoundingClientRect(); menu.style.left = `${Math.min(rect.left, window.innerWidth - 230)}px`; menu.style.top = `${rect.bottom + 5}px`; menu.hidden = false; activeFilterColumn = column; menu.querySelector('.filter-menu-search').addEventListener('input', e => menu.querySelectorAll('.filter-value').forEach(item => { item.hidden = !item.textContent.toLowerCase().includes(e.target.value.toLowerCase()); })); menu.querySelector('#clearColumnFilter').addEventListener('click', () => { delete state.columnFilters[column]; persist(); menu.hidden = true; render(); }); menu.querySelector('#applyColumnFilter').addEventListener('click', () => { const checked = [...menu.querySelectorAll('[data-filter-value]:checked')].map(input => input.dataset.filterValue); state.columnFilters[column] = checked.length === values.length ? [] : checked; persist(); menu.hidden = true; render(); }); }
function normalizeCommand(command) { return command.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim(); }
function removeDuplicateValues() { const sheet = currentSheet(); const seen = new Set(); let removed = 0; pushHistory(); sheet.cells.forEach(row => row.forEach((value, col) => { const normalized = String(value).trim().toLowerCase(); if (!normalized) return; if (seen.has(normalized)) { row[col] = ''; removed++; } else seen.add(normalized); })); persist(); render(); toast(removed ? `${removed} duplicado(s) excluído(s)` : 'Nenhum duplicado encontrado'); }
function removeEmptyRows() { const sheet = currentSheet(), lastUsed = sheet.cells.reduce((last, row, index) => row.some(value => String(value).trim()) ? index : last, -1); if (lastUsed < 0) return toast('Nenhuma linha preenchida encontrada'); const kept = [], keptColors = [], keptFormats = []; for (let index = 0; index <= lastUsed; index++) { if (sheet.cells[index].some(value => String(value).trim())) { kept.push(sheet.cells[index]); keptColors.push(sheet.colors[index]); keptFormats.push(sheet.formats[index]); } } const removed = lastUsed + 1 - kept.length; if (!removed) return toast('Nenhuma linha vazia encontrada'); pushHistory(); sheet.cells.splice(0, lastUsed + 1, ...kept); sheet.colors.splice(0, lastUsed + 1, ...keptColors); sheet.formats.splice(0, lastUsed + 1, ...keptFormats); persist(); render(); toast(`${removed} linha(s) vazia(s) excluída(s)`); }
function clearCurrentSheet() { const sheet = currentSheet(); pushHistory(); sheet.cells = Array.from({ length: PAGE_SIZE.rows }, () => Array(PAGE_SIZE.cols).fill('')); sheet.colors = Array.from({ length: PAGE_SIZE.rows }, () => Array(PAGE_SIZE.cols).fill('')); sheet.formats = Array.from({ length: PAGE_SIZE.rows }, () => Array.from({ length: PAGE_SIZE.cols }, () => ({}))); delete state.columnFilters; state.columnFilters = {}; persist(); render(); toast('Página limpa'); }
function normalizeCellSeparators() { const sheet = currentSheet(); let changed = 0; pushHistory(); sheet.cells.forEach(row => row.forEach((value, col) => { const normalized = String(value).replace(/[;\n]+/g, ', ').replace(/\s*,\s*/g, ', ').replace(/(?:, ){2,}/g, ', ').trim(); if (normalized !== value) { row[col] = normalized; changed++; } })); persist(); render(); toast(changed ? `${changed} célula(s) ajustada(s)` : 'As células já estão padronizadas'); }
function consolidateDisciplines() { const sheet = currentSheet(), groups = new Map(); let removed = 0, changed = 0; sheet.cells.forEach((row, index) => { const discipline = String(row[0] ?? '').trim(); if (!discipline) return; const key = discipline.toLowerCase(); if (!groups.has(key)) groups.set(key, { index, discipline, codes: new Set() }); const group = groups.get(key); String(row[1] ?? '').split(/[,;\n]+/).map(code => code.trim()).filter(Boolean).forEach(code => group.codes.add(code)); if (group.index !== index) { row.forEach((_, col) => { row[col] = ''; }); removed++; } }); groups.forEach(group => { const row = sheet.cells[group.index]; const codes = [...group.codes].join(', '); if (row[0] !== group.discipline || row[1] !== codes) { row[0] = group.discipline; row[1] = codes; changed++; } }); persist(); render(); toast(removed ? `${removed} duplicada(s) removida(s), ${changed} disciplina(s) consolidada(s)` : 'Nenhuma disciplina duplicada encontrada'); }
function analyzeSheet() { const sheet = currentSheet(), filled = sheet.cells.flat().filter(value => String(value).trim()).length, emptyRows = sheet.cells.filter(row => !row.some(value => String(value).trim())).length, counts = new Map(); sheet.cells.flat().forEach(value => { const normalized = String(value).trim().toLowerCase(); if (normalized) counts.set(normalized, (counts.get(normalized) || 0) + 1); }); const duplicates = [...counts.values()].filter(count => count > 1).reduce((total, count) => total + count - 1, 0); toast(`${filled} preenchida(s), ${duplicates} duplicada(s), ${emptyRows} linha(s) vazia(s)`); }
function paintColumn(column, color) { const columnNumber = columnIndex(column), sheet = currentSheet(); if (columnNumber < 0) return toast('Coluna inválida'); ensureSheetSize(sheet, pageSize().rows, columnNumber + 1); pushHistory(); sheet.colors.forEach(row => { row[columnNumber] = color; }); persist(); render(); toast(`Coluna ${column} pintada`); }
function colorValue(value) { const colors = { amarelo: '#fff3a3', azul: '#b9dcff', verde: '#c9f2b1', vermelho: '#ffc4c4', rosa: '#f7c4e8', laranja: '#ffd2a6', roxo: '#ddc7ff', cinza: '#d9dee5', branco: '' }; return /^#[0-9a-f]{6}$/i.test(value) ? value : colors[value.toLowerCase()] ?? null; }
function applyAssistantCommand(command) {
  const normalized = normalizeCommand(command);
  if (!normalized) return toast('Digite uma alteração');
  const steps = command.split(/\s+(?:e depois|depois|entao|então)\s+|;/i).map(step => step.trim()).filter(Boolean);
  if (steps.length > 1) { steps.forEach(step => applyAssistantCommand(step)); toast(`${steps.length} etapas concluídas`); return; }
  if (/^(analise|analisar|diagnostique|diagnosticar|verifique|verificar) (a )?(planilha|tabela|dados)/.test(normalized)) { analyzeSheet(); return; }
  if (/(corrija|corrigir|resolva|resolver|organize|organizar).*(problema|problemas|erro|erros|inconsist)/.test(normalized)) { normalizeCellSeparators(); removeDuplicateValues(); removeEmptyRows(); toast('Problemas da planilha corrigidos'); return; }
  if (/^(limpe|limpar|apague|apagar|delete) (a )?(pagina|planilha|tabela)$/.test(normalized) || /^(limpe|limpar) tudo$/.test(normalized)) { clearCurrentSheet(); return; }
  const paintMatch = normalized.match(/(?:pinte|pintar|colorir|colora) (?:a )?(?:coluna )?([a-z]+) (?:de|com) ([a-z]+|#[0-9a-f]{6})/i);
  if (paintMatch) { const color = colorValue(paintMatch[2]); if (color === null) return toast('Cor não reconhecida'); paintColumn(paintMatch[1].toUpperCase(), color); return; }
  if (/^(exclua|excluir|remova|remover|apague|apagar) (as )?(linhas )?(vazias|em branco)$/.test(normalized) || /(exclua|excluir|remova|remover|apague|apagar).*(linhas|linha).*(vazias|em branco)/.test(normalized)) { removeEmptyRows(); return; }
  if (/(exclua|excluir|remova|remover|apague|apagar).*(duplicad|repetid).*(codigo|codigos|disciplina)|((junte|juntar|adicione|adicionar).*(codigo|codigos).*(disciplina|linha))/.test(normalized)) { consolidateDisciplines(); return; }
  if (/^(exclua|excluir|remova|remover|apague|apagar) (os )?(valores )?duplicados$/.test(normalized)) { removeDuplicateValues(); return; }
  if (/^(adicione|adicionar|coloque|colocar|insira|inserir) (uma )?(virgula|virgula e espaco|virgulas e espacos) (dentro|entre) (de )?(cada|todas as) celulas?$/.test(normalized) || /^(padronize|padronizar) (as )?(virgulas|separadores)/.test(normalized)) { normalizeCellSeparators(); return; }
  if (/^(adicione|adicionar|crie|criar) (uma )?(linha|linhas)$/.test(normalized)) { pushHistory(); currentSheet().cells.push(Array(pageSize().cols).fill('')); render(); persist(); toast('Linha adicionada'); return; }
  if (/^(adicione|adicionar|crie|criar) (uma )?(coluna|colunas)$/.test(normalized)) { pushHistory(); currentSheet().cells.forEach(row => row.push('')); render(); persist(); toast('Coluna adicionada'); return; }
  if (/^(insira|inserir|adicione|adicionar) (o )?(exemplo|modelo)$/.test(normalized)) { document.querySelector('[data-action="sample"]').click(); return; }
  const sumMatch = normalized.match(/(?:some|somar|calcule a soma de) ([a-z]+\d+:[a-z]+\d+) (?:em|na celula|na célula) ([a-z]+\d+)/);
  if (sumMatch) { const target = sumMatch[2].toUpperCase(), range = sumMatch[1].toUpperCase(); applyAssistantCommand(`preencha ${target} com =SUM(${range})`); return; }
  const multiplyMatch = normalized.match(/(?:multiplique|multiplicar|calcule o produto de) ([a-z]+\d+) (?:por|vezes) ([a-z]+\d+) (?:em|na celula|na célula) ([a-z]+\d+)/);
  if (multiplyMatch) { const target = multiplyMatch[3].toUpperCase(); applyAssistantCommand(`preencha ${target} com =${multiplyMatch[1].toUpperCase()}*${multiplyMatch[2].toUpperCase()}`); return; }
  const clearMatch = normalized.match(/^(limpe|limpar|apague|apagar|delete) (a celula )?([a-z]+\d+)$/);
  if (clearMatch) { const match = clearMatch[3].match(/([a-z]+)(\d+)/); const row = Number(match[2]) - 1, col = columnIndex(match[1].toUpperCase()); if (row < 0 || col < 0) return toast('Célula inválida'); ensureSheetSize(currentSheet(), row + 1, col + 1); pushHistory(); currentSheet().cells[row][col] = ''; render(); persist(); toast(`Célula ${match[3].toUpperCase()} limpa`); return; }
  const fillMatch = command.match(/^(?:preencha|preencher|insira|inserir|coloque|colocar)\s+(?:a\s+)?(?:celula\s+)?([A-Z]+\d+)\s+(?:com|:|=)\s*(.*)$/i);
  if (fillMatch) { const match = fillMatch[1].match(/([A-Z]+)(\d+)/i); const row = Number(match[2]) - 1, col = columnIndex(match[1].toUpperCase()); if (row < 0 || col < 0) return toast('Célula inválida'); ensureSheetSize(currentSheet(), row + 1, col + 1); pushHistory(); currentSheet().cells[row][col] = fillMatch[2].trim().replace(/^("|')(.*)\1$/, '$2'); persist(); render(); selectCell(row, col, false); toast(`Célula ${fillMatch[1].toUpperCase()} preenchida`); return; }
  toast('Não reconheci. Tente: “analise a planilha”, “corrija os problemas” ou “some C2:C10 em D11”');
}
function escapeHtml(value) { return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;'); }
function copyCell() { clipboardBuffer = currentSheet().cells[activeCell.row]?.[activeCell.col] || ''; navigator.clipboard?.writeText(clipboardBuffer).catch(() => {}); toast('Célula inteira copiada'); }
function pasteText(text) { if (!text) return; const values = text.replace(/\r/g, '').split('\n').filter((row, index, rows) => row || index < rows.length - 1).map(row => row.split('\t')); const { rows, cols } = pageSize(); const height = Math.max(rows, activeCell.row + values.length), width = Math.max(cols, activeCell.col + Math.max(...values.map(row => row.length))); ensureSheetSize(currentSheet(), height, width); pushHistory(); values.forEach((row, rowOffset) => row.forEach((value, colOffset) => { currentSheet().cells[activeCell.row + rowOffset][activeCell.col + colOffset] = value; })); persist(); render(); selectCell(activeCell.row, activeCell.col, false); toast('Conteúdo colado'); }

grid.addEventListener('focusin', e => { if (e.target.classList.contains('cell')) selectCell(+e.target.dataset.row, +e.target.dataset.col, false); });
grid.addEventListener('mousedown', e => { const cell = e.target.closest('.cell'); if (!cell || e.button !== 0) return; dragClearActive = true; dragClearMoved = false; dragClearCells = new Set([`${cell.dataset.row}:${cell.dataset.col}`]); });
grid.addEventListener('mouseover', e => { const cell = e.target.closest('.cell'); if (!dragClearActive || !cell || !(e.buttons & 1)) return; const key = `${cell.dataset.row}:${cell.dataset.col}`; if (dragClearCells.has(key)) return; dragClearMoved = true; dragClearCells.add(key); });
document.addEventListener('mouseup', () => { if (!dragClearActive) return; if (dragClearMoved) { const sheet = currentSheet(); const changed = [...dragClearCells].some(key => { const [row, col] = key.split(':').map(Number); return String(sheet.cells[row]?.[col] || '').trim() || sheet.colors[row]?.[col] || Object.keys(sheet.formats[row]?.[col] || {}).length; }); if (changed) { pushHistory(); dragClearCells.forEach(key => { const [row, col] = key.split(':').map(Number); sheet.cells[row][col] = ''; sheet.colors[row][col] = ''; sheet.formats[row][col] = {}; }); persist(); render(); toast('Células limpas'); } } dragClearActive = false; dragClearMoved = false; dragClearCells = new Set(); });
grid.addEventListener('click', e => { const button = e.target.closest('[data-filter-column]'); if (button) { e.stopPropagation(); openFilterMenu(Number(button.dataset.filterColumn), button); } });
grid.addEventListener('change', e => { if (!e.target.matches('[data-column-name]')) return; const column = Number(e.target.dataset.columnName); const sheet = currentSheet(); const name = e.target.value.trim() || columnName(column); pushHistory(); sheet.columnNames[column] = name; persist(); render(); });
grid.addEventListener('focusout', e => { if (e.target.classList.contains('cell')) { const value = e.target.textContent.trim(); if (e.target.dataset.formula === 'true' && displayValue(currentSheet().cells[+e.target.dataset.row][+e.target.dataset.col]) === value) return; commitCell(e.target, value); } });
grid.addEventListener('copy', e => { if (!e.target.classList.contains('cell')) return; clipboardBuffer = currentSheet().cells[+e.target.dataset.row][+e.target.dataset.col] || ''; e.clipboardData.setData('text/plain', clipboardBuffer); e.clipboardData.setData('text/html', `<table><tbody><tr><td>${escapeHtml(clipboardBuffer)}</td></tr></tbody></table>`); e.preventDefault(); toast('Célula inteira copiada'); });
grid.addEventListener('paste', e => { if (!e.target.classList.contains('cell')) return; e.preventDefault(); pasteText(e.clipboardData.getData('text/plain')); });
grid.addEventListener('keydown', e => { if (!e.target.classList.contains('cell')) return; const row = +e.target.dataset.row, col = +e.target.dataset.col; if (e.key === 'Enter') { e.preventDefault(); commitCell(e.target, e.target.textContent.trim()); selectCell(Math.min(pageSize().rows - 1, row + 1), col); } if (e.key === 'Tab') { e.preventDefault(); commitCell(e.target, e.target.textContent.trim()); selectCell(row, Math.min(pageSize().cols - 1, col + 1)); } if (e.key === 'Escape') { e.target.innerHTML = displayValue(currentSheet().cells[row][col]); e.target.blur(); } });
formulaInput.addEventListener('input', () => { currentSheet().cells[activeCell.row][activeCell.col] = formulaInput.value; const cell = document.querySelector(`[data-row="${activeCell.row}"][data-col="${activeCell.col}"]`); if (cell) { cell.innerHTML = displayValue(formulaInput.value); cell.classList.toggle('formula', formulaInput.value.startsWith('=')); } });
formulaInput.addEventListener('keydown', e => { if (e.key === 'Enter') { pushHistory(); persist(); selectCell(activeCell.row, activeCell.col); } });
document.getElementById('fileName').addEventListener('change', e => { state.fileName = e.target.value || 'Meu planejamento'; persist(); });
document.getElementById('addSheet').addEventListener('click', () => { pushHistory(); state.sheets.push(blankSheet(`Aba ${state.sheets.length + 1}`)); state.active = state.sheets.length - 1; persist(); render(); });
document.getElementById('sheetTabs').addEventListener('click', e => { if (!e.target.dataset.sheet) return; state.active = +e.target.dataset.sheet; activeCell = {row:0,col:0}; render(); });
document.getElementById('importButton').addEventListener('click', () => document.getElementById('fileInput').click());
function readSpreadsheet(data) { try { return XLSX.read(data, {type:'array', cellDates:true, cellNF:true, cellText:true, WTF:false}); } catch (error) { if (!(data instanceof ArrayBuffer)) throw error; let binary = ''; const bytes = new Uint8Array(data); for (let index = 0; index < bytes.length; index++) binary += String.fromCharCode(bytes[index]); return XLSX.read(binary, {type:'binary', cellDates:true, cellNF:true, cellText:true, WTF:false}); } }
document.getElementById('fileInput').addEventListener('change', e => { const file = e.target.files[0]; if (!file) return; const extension = file.name.split('.').pop().toLowerCase(); const reader = new FileReader(); reader.onload = event => { try { const workbook = readSpreadsheet(event.target.result); if (!workbook.SheetNames.length) throw new Error('Arquivo sem abas'); const { rows: pageRows, cols: pageCols } = pageSize(); state.sheets = workbook.SheetNames.map(name => { const sourceRows = XLSX.utils.sheet_to_json(workbook.Sheets[name], {header:1, defval:'', raw:false, blankrows:true}); const width = Math.max(pageCols, ...sourceRows.map(row => row.length), 0); const height = Math.max(pageRows, sourceRows.length); return {name: String(name).slice(0, 31) || 'Planilha', columnNames: Array.from({length: width}, (_, index) => columnName(index)), cells:Array.from({length:height}, (_,r) => Array.from({length:width}, (_,c) => String(sourceRows[r]?.[c] ?? ''))), colors:Array.from({length:height}, () => Array(width).fill('')), formats:Array.from({length:height}, () => Array.from({length:width}, () => ({}))) }; }); state.active=0; state.fileName=file.name.replace(/\.[^.]+$/, '') || 'planilha'; state.columnFilters = {}; persist(true); render(); toast(`${state.sheets.length} aba(s) importada(s)`); } catch (error) { console.error('Falha ao importar planilha:', error); toast(extension === 'et' || extension === 'ett' || extension === 'wps' ? 'Não foi possível ler este arquivo WPS. Se for uma planilha, salve uma cópia como XLSX no WPS e importe novamente.' : 'Não foi possível ler este arquivo Excel. Verifique se ele não está protegido por senha.'); } }; reader.onerror = () => toast('Não foi possível abrir o arquivo'); reader.readAsArrayBuffer(file); e.target.value=''; });
document.getElementById('exportButton').addEventListener('click', () => { const workbook = XLSX.utils.book_new(); state.sheets.forEach(sheet => { const data = sheet.cells.map(row => row.map(value => value.startsWith('=') ? {f:value.slice(1)} : value)); XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet(data), sheet.name.slice(0,31)); }); XLSX.writeFile(workbook, `${state.fileName || 'planilha'}.xlsx`); toast('Excel exportado'); });
document.querySelectorAll('[data-action]').forEach(button => button.addEventListener('click', () => { const action = button.dataset.action; if (action === 'clear') { pushHistory(); currentSheet().cells[activeCell.row][activeCell.col] = ''; render(); persist(); } if (action === 'add-row') { pushHistory(); currentSheet().cells.push(Array(pageSize().cols).fill('')); render(); persist(); } if (action === 'add-column') { pushHistory(); const sheet = currentSheet(); sheet.cells.forEach(row => row.push('')); sheet.columnNames.push(columnName(sheet.columnNames.length)); render(); persist(); } if (action === 'sample') { pushHistory(); currentSheet().cells[0] = ['Item','Categoria','Quantidade','Valor unitário','Total']; currentSheet().cells[1] = ['Caderno','Escritório','12','18.5','=C2*D2']; currentSheet().cells[2] = ['Caneta','Escritório','30','3.2','=C3*D3']; currentSheet().cells[3] = ['Café','Copa','8','24','=C4*D4']; render(); persist(); toast('Exemplo adicionado'); } }));
document.getElementById('cellColor').addEventListener('input', e => { const sheet = currentSheet(); ensureSheetSize(sheet, activeCell.row + 1, activeCell.col + 1); pushHistory(); sheet.colors[activeCell.row][activeCell.col] = e.target.value === '#ffffff' ? '' : e.target.value; persist(); render(); selectCell(activeCell.row, activeCell.col, false); });
document.querySelectorAll('[data-format]').forEach(button => button.addEventListener('click', () => { const sheet = currentSheet(); ensureSheetSize(sheet, activeCell.row + 1, activeCell.col + 1); const format = sheet.formats[activeCell.row][activeCell.col] || {}; const action = button.dataset.format; pushHistory(); if (action === 'bold') format.bold = !format.bold; if (action === 'italic') format.italic = !format.italic; if (action === 'align') format.align = format.align === 'center' ? 'right' : format.align === 'right' ? 'left' : 'center'; sheet.formats[activeCell.row][activeCell.col] = format; persist(); render(); selectCell(activeCell.row, activeCell.col, false); }));
const assistantDialog = document.getElementById('assistantDialog');
const assistantInput = document.getElementById('assistantInput');
function assistantSheetContext() { const sheet = currentSheet(); return { name: sheet.name, columnNames: sheet.columnNames, cells: sheet.cells.filter(row => row.some(value => String(value).trim())).slice(0, 120) }; }
async function requestAssistantCommand(command) { const endpoint = window.ASSISTANT_API_URL || '/api/assistant'; try { const result = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ command, sheet: assistantSheetContext() }) }); if (!result.ok) throw new Error('Assistente remoto indisponível'); const data = await result.json(); if (!data.command) throw new Error('Resposta inválida'); if (data.reply) toast(data.reply); return data.command; } catch (_) { return command; } }
document.getElementById('assistantButton').addEventListener('click', () => { assistantDialog.showModal(); assistantInput.focus(); });
document.getElementById('assistantForm').addEventListener('submit', async e => { e.preventDefault(); const command = assistantInput.value.trim(); if (!command) return toast('Digite uma alteração'); const button = document.getElementById('applyAssistant'); button.disabled = true; button.textContent = 'Interpretando...'; const interpretedCommand = await requestAssistantCommand(command); applyAssistantCommand(interpretedCommand); assistantInput.value = ''; button.disabled = false; button.textContent = 'Aplicar alteração'; assistantDialog.close(); });
document.getElementById('copyButton').addEventListener('click', copyCell);
document.getElementById('pasteButton').addEventListener('click', async () => { if (clipboardBuffer) return pasteText(clipboardBuffer); try { pasteText(await navigator.clipboard.readText()); } catch (_) { toast('Nada para colar'); } });
document.getElementById('searchInput').addEventListener('input', applySearch);
function setZoom(value) { const zoom = Math.max(50, Math.min(200, Number(value) || 100)); state.zoom = Math.round(zoom / 10) * 10; persist(); render(); }
document.getElementById('zoomInput').addEventListener('change', e => setZoom(e.target.value));
document.getElementById('zoomInput').addEventListener('keydown', e => { if (e.key === 'Enter') { setZoom(e.target.value); e.target.blur(); } });
document.getElementById('zoomOut').addEventListener('click', () => setZoom(state.zoom - 10));
document.getElementById('zoomIn').addEventListener('click', () => setZoom(state.zoom + 10));
const settingsDialog = document.getElementById('settingsDialog');
document.getElementById('settingsButton').addEventListener('click', () => { document.getElementById('settingsZoom').value = state.zoom; document.getElementById('settingsDensity').value = state.settings.density; document.getElementById('settingsSelectionColor').value = state.settings.selectionColor; document.getElementById('settingsGridTheme').value = state.settings.gridTheme; document.getElementById('settingsGridlines').checked = state.settings.gridlines; document.getElementById('settingsAutoSave').checked = state.settings.autoSave; settingsDialog.showModal(); });
document.getElementById('settingsForm').addEventListener('submit', e => { e.preventDefault(); state.zoom = Math.max(50, Math.min(200, Math.round((Number(document.getElementById('settingsZoom').value) || 100) / 10) * 10)); state.settings = { density: document.getElementById('settingsDensity').value, selectionColor: document.getElementById('settingsSelectionColor').value, gridTheme: document.getElementById('settingsGridTheme').value, gridlines: document.getElementById('settingsGridlines').checked, autoSave: document.getElementById('settingsAutoSave').checked }; persist(true); render(); settingsDialog.close(); toast('Configurações aplicadas'); });
function applySearch() { const query = document.getElementById('searchInput').value.toLowerCase(); document.querySelectorAll('.cell').forEach(cell => cell.classList.toggle('search-hit', query && cell.textContent.toLowerCase().includes(query))); }
document.getElementById('undoButton').addEventListener('click', () => { if (historyIndex < 0) return toast('Nada para desfazer'); state = JSON.parse(history[historyIndex--]); render(); persist(); });
document.getElementById('redoButton').addEventListener('click', () => toast('Use Ctrl+Z para desfazer alterações'));
document.addEventListener('keydown', e => { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 's') { e.preventDefault(); persist(true); toast('Alterações salvas'); } });
render();
